title:
  it: Tutto ció che non è donato è perduto
  en: All is not given is lost
email: trepreciso@gmail.com
description:
  en: A collection of ideas, how-to and best practices that I consider worth sharing
  it: Idee, suggerimenti e guide che trovo utile condividere
baseurl: ""
url: https://erpreciso.github.io
# twitter_username: jekyllrb
github_username:  erpreciso

# global flag to show excerpts in home
show_excerpts: true

index:
  en: index.html
  it: indice.html

# Build settings
markdown: kramdown
theme: minima
plugins_dir:
  - jekyll-feed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-maps

# compress html template http://jch.penibelst.de/
#
compress_html:
    clippings: [all]
    comments: [all]
    ignore:
      envs: [local]

# google analytics plugin
google_analytics: UA-54837961-3

# maps key
maps:
  google:
    api_key: AIzaSyAcL3GY_81kL6edpJ6zRwEu5Qpy0DqhGUw
    marker_cluster:
      enabled: true

# Minima date format
# # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%e %B %Y"

# default values for static files
defaults:
  -
    scope:
      path: "assets/images/pamir/gallery"
    values:
      pamir: true
  -
    scope:
      path: "assets/images/iceland/2011/gallery"
    values:
      iceland_2011: true
  -
    scope:
      path: "assets/images/iceland/2012/gallery"
    values:
      iceland_2012: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - TODO.txt
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

