title:
  it: Tutto ció che non è donato è perduto
  en: All is not given is lost
email: trepreciso@gmail.com
description:
  en: A collection of ideas, how-to and best practices that I consider worth sharing
  it: Idee, suggerimenti e guide che trovo utile condividere
baseurl: ""
url: https://erpreciso.github.io
# twitter_username: jekyllrb
github_username:  erpreciso
show_excerpts: true


# Build settings
markdown: kramdown
theme: minima
plugins_dir:
  - jekyll-feed

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics: UA-54837961-3

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - TODO.txt
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

